[2024-06-22T12:07:58.066+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_regression manual__2024-06-22T12:07:48.229499+00:00 [queued]>
[2024-06-22T12:07:58.081+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_regression manual__2024-06-22T12:07:48.229499+00:00 [queued]>
[2024-06-22T12:07:58.082+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-06-22T12:07:58.101+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_modeling_regression> on 2024-06-22 12:07:48.229499+00:00
[2024-06-22T12:07:58.112+0000] {standard_task_runner.py:60} INFO - Started process 2375 to run task
[2024-06-22T12:07:58.116+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'DAG_ml_pipeline_class_reg', 'run_modeling_regression', 'manual__2024-06-22T12:07:48.229499+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/run_data_wrangling_class_reg.py', '--cfg-path', '/tmp/tmpm2l850ge']
[2024-06-22T12:07:58.127+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask run_modeling_regression
[2024-06-22T12:07:58.182+0000] {task_command.py:423} INFO - Running <TaskInstance: DAG_ml_pipeline_class_reg.run_modeling_regression manual__2024-06-22T12:07:48.229499+00:00 [running]> on host 0fdcf3d7bc80
[2024-06-22T12:07:58.264+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_ml_pipeline_class_reg' AIRFLOW_CTX_TASK_ID='run_modeling_regression' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T12:07:48.229499+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T12:07:48.229499+00:00'
[2024-06-22T12:07:58.268+0000] {logging_mixin.py:188} INFO - Looking for .env file at: /opt/***/config/.env
[2024-06-22T12:07:58.290+0000] {credentials.py:1278} INFO - Found credentials in shared credentials file: ~/.aws/credentials
[2024-06-22T12:08:01.412+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeRegressor from version 1.4.1.post1 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

[2024-06-22T12:08:01.426+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator RandomForestRegressor from version 1.4.1.post1 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

[2024-06-22T12:08:01.427+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

[2024-06-22T12:08:03.081+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 183, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 182, in executemany
    return self._do_execute_many(
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 220, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '5396524' for key 'demurrage_predictor_data.PRIMARY'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/modeling_reg_tasks/modeling_reg.py", line 111, in main_modeling_reg
    load_data_to_mysql(merged_df, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT , DB_NAME, DB_TABLE)
  File "/opt/airflow/dags/modeling_reg_tasks/modeling_reg.py", line 38, in load_data_to_mysql
    merged_df.to_sql(name=table_name, con=engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1920, in to_sql
    total_inserted = sql_engine.insert_records(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1470, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1461, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1023, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 929, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 183, in do_executemany
    rowcount = cursor.executemany(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 182, in executemany
    return self._do_execute_many(
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 220, in _do_execute_many
    rows += self.execute(sql + postfix)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.IntegrityError: (pymysql.err.IntegrityError) (1062, "Duplicate entry '5396524' for key 'demurrage_predictor_data.PRIMARY'")
[SQL: INSERT INTO demurrage_predictor_data (sku, estimated_price, number_of_products_sold, stock_levels, lead_times, order_quantities, shipping_times, shipping_carriers, shipping_costs, location, production_volumes, manufacturing_lead_time, manufacturing_costs, inspection_results, defect_rates, transportation_modes, routes, costs, demurrage_cost_prediction, demurrage_bin) VALUES (%(sku)s, %(estimated_price)s, %(number_of_products_sold)s, %(stock_levels)s, %(lead_times)s, %(order_quantities)s, %(shipping_times)s, %(shipping_carriers)s, %(shipping_costs)s, %(location)s, %(production_volumes)s, %(manufacturing_lead_time)s, %(manufacturing_costs)s, %(inspection_results)s, %(defect_rates)s, %(transportation_modes)s, %(routes)s, %(costs)s, %(demurrage_cost_prediction)s, %(demurrage_bin)s)]
[parameters: ({'sku': 5396524, 'estimated_price': 6718.076802, 'number_of_products_sold': 333.3557071, 'stock_levels': 73.94330402, 'lead_times': 8.581356389, 'order_quantities': 3.603537662, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 351.0, 'location': 'Mumbai', 'production_volumes': 87.87218592, 'manufacturing_lead_time': 24.18368624, 'manufacturing_costs': 87.21, 'inspection_results': 'Pending', 'defect_rates': 3.62, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 302.18, 'demurrage_cost_prediction': 53.89950000000001, 'demurrage_bin': 1}, {'sku': 5399340, 'estimated_price': 13435.78575, 'number_of_products_sold': 356.3596194, 'stock_levels': 62.34920921, 'lead_times': 16.62794728, 'order_quantities': 22.05155158, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 473.0, 'location': 'Bangalore', 'production_volumes': 449.7892775, 'manufacturing_lead_time': 11.61745016, 'manufacturing_costs': 79.25, 'inspection_results': 'Fail', 'defect_rates': 6.52, 'transportation_modes': 'Rail', 'routes': 'D route', 'costs': 457.9, 'demurrage_cost_prediction': 43.281499999999994, 'demurrage_bin': 1}, {'sku': 2461025, 'estimated_price': 3665.165803, 'number_of_products_sold': 785.7249661, 'stock_levels': 98.47805287, 'lead_times': 2.882424374, 'order_quantities': 60.60993842, 'shipping_times': 1.0, 'shipping_carriers': 'Carrier C', 'shipping_costs': 803.0, 'location': 'Mumbai', 'production_volumes': 301.4595301, 'manufacturing_lead_time': 21.06348163, 'manufacturing_costs': 93.77, 'inspection_results': 'Fail', 'defect_rates': 5.07, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 722.4, 'demurrage_cost_prediction': 46.08089999999999, 'demurrage_bin': 1}, {'sku': 2462250, 'estimated_price': 38863.50033, 'number_of_products_sold': 368.3484985, 'stock_levels': 66.43820947, 'lead_times': 16.69870172, 'order_quantities': 5.144399512, 'shipping_times': 9.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 470.0, 'location': 'Mumbai', 'production_volumes': 105.7488657, 'manufacturing_lead_time': 14.1989102, 'manufacturing_costs': 55.3, 'inspection_results': 'Pass', 'defect_rates': 2.53, 'transportation_modes': 'Road', 'routes': 'D route', 'costs': 503.18, 'demurrage_cost_prediction': 48.3367, 'demurrage_bin': 1}, {'sku': 2465025, 'estimated_price': 6275.178231, 'number_of_products_sold': 535.1241272, 'stock_levels': 35.22678102, 'lead_times': 16.13447074, 'order_quantities': 97.74552431, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier B', 'shipping_costs': 0.0, 'location': 'Mumbai', 'production_volumes': 12.28655797, 'manufacturing_lead_time': 9.63366577, 'manufacturing_costs': 60.22, 'inspection_results': 'Fail', 'defect_rates': 4.07, 'transportation_modes': 'Road', 'routes': 'Route_B', 'costs': 563.07, 'demurrage_cost_prediction': 54.42549999999999, 'demurrage_bin': 1}, {'sku': 2409620, 'estimated_price': 8251.96252, 'number_of_products_sold': 696.1544255, 'stock_levels': 44.24509383, 'lead_times': 7.764919693, 'order_quantities': 69.66251389, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier B', 'shipping_costs': 533.0, 'location': 'Mumbai', 'production_volumes': 554.9156217, 'manufacturing_lead_time': 6.573059301, 'manufacturing_costs': 69.45, 'inspection_results': 'Fail', 'defect_rates': 1.56, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 506.19, 'demurrage_cost_prediction': 59.601800000000004, 'demurrage_bin': 1}, {'sku': 3210626, 'estimated_price': 56945.72832, 'number_of_products_sold': 161.4287572, 'stock_levels': 48.13790727, 'lead_times': 17.33553905, 'order_quantities': 60.25554524, 'shipping_times': 1.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 220.0, 'location': 'Bangalore', 'production_volumes': 128.6387942, 'manufacturing_lead_time': 8.124497762, 'manufacturing_costs': 92.2, 'inspection_results': 'Fail', 'defect_rates': 1.89, 'transportation_modes': 'Rail', 'routes': 'D route', 'costs': 786.93, 'demurrage_cost_prediction': 51.75320000000002, 'demurrage_bin': 1})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-06-22T12:08:03.099+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=DAG_ml_pipeline_class_reg, task_id=run_modeling_regression, execution_date=20240622T120748, start_date=20240622T120758, end_date=20240622T120803
[2024-06-22T12:08:03.120+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task run_modeling_regression ((pymysql.err.IntegrityError) (1062, "Duplicate entry '5396524' for key 'demurrage_predictor_data.PRIMARY'")
[SQL: INSERT INTO demurrage_predictor_data (sku, estimated_price, number_of_products_sold, stock_levels, lead_times, order_quantities, shipping_times, shipping_carriers, shipping_costs, location, production_volumes, manufacturing_lead_time, manufacturing_costs, inspection_results, defect_rates, transportation_modes, routes, costs, demurrage_cost_prediction, demurrage_bin) VALUES (%(sku)s, %(estimated_price)s, %(number_of_products_sold)s, %(stock_levels)s, %(lead_times)s, %(order_quantities)s, %(shipping_times)s, %(shipping_carriers)s, %(shipping_costs)s, %(location)s, %(production_volumes)s, %(manufacturing_lead_time)s, %(manufacturing_costs)s, %(inspection_results)s, %(defect_rates)s, %(transportation_modes)s, %(routes)s, %(costs)s, %(demurrage_cost_prediction)s, %(demurrage_bin)s)]
[parameters: ({'sku': 5396524, 'estimated_price': 6718.076802, 'number_of_products_sold': 333.3557071, 'stock_levels': 73.94330402, 'lead_times': 8.581356389, 'order_quantities': 3.603537662, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 351.0, 'location': 'Mumbai', 'production_volumes': 87.87218592, 'manufacturing_lead_time': 24.18368624, 'manufacturing_costs': 87.21, 'inspection_results': 'Pending', 'defect_rates': 3.62, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 302.18, 'demurrage_cost_prediction': 53.89950000000001, 'demurrage_bin': 1}, {'sku': 5399340, 'estimated_price': 13435.78575, 'number_of_products_sold': 356.3596194, 'stock_levels': 62.34920921, 'lead_times': 16.62794728, 'order_quantities': 22.05155158, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 473.0, 'location': 'Bangalore', 'production_volumes': 449.7892775, 'manufacturing_lead_time': 11.61745016, 'manufacturing_costs': 79.25, 'inspection_results': 'Fail', 'defect_rates': 6.52, 'transportation_modes': 'Rail', 'routes': 'D route', 'costs': 457.9, 'demurrage_cost_prediction': 43.281499999999994, 'demurrage_bin': 1}, {'sku': 2461025, 'estimated_price': 3665.165803, 'number_of_products_sold': 785.7249661, 'stock_levels': 98.47805287, 'lead_times': 2.882424374, 'order_quantities': 60.60993842, 'shipping_times': 1.0, 'shipping_carriers': 'Carrier C', 'shipping_costs': 803.0, 'location': 'Mumbai', 'production_volumes': 301.4595301, 'manufacturing_lead_time': 21.06348163, 'manufacturing_costs': 93.77, 'inspection_results': 'Fail', 'defect_rates': 5.07, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 722.4, 'demurrage_cost_prediction': 46.08089999999999, 'demurrage_bin': 1}, {'sku': 2462250, 'estimated_price': 38863.50033, 'number_of_products_sold': 368.3484985, 'stock_levels': 66.43820947, 'lead_times': 16.69870172, 'order_quantities': 5.144399512, 'shipping_times': 9.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 470.0, 'location': 'Mumbai', 'production_volumes': 105.7488657, 'manufacturing_lead_time': 14.1989102, 'manufacturing_costs': 55.3, 'inspection_results': 'Pass', 'defect_rates': 2.53, 'transportation_modes': 'Road', 'routes': 'D route', 'costs': 503.18, 'demurrage_cost_prediction': 48.3367, 'demurrage_bin': 1}, {'sku': 2465025, 'estimated_price': 6275.178231, 'number_of_products_sold': 535.1241272, 'stock_levels': 35.22678102, 'lead_times': 16.13447074, 'order_quantities': 97.74552431, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier B', 'shipping_costs': 0.0, 'location': 'Mumbai', 'production_volumes': 12.28655797, 'manufacturing_lead_time': 9.63366577, 'manufacturing_costs': 60.22, 'inspection_results': 'Fail', 'defect_rates': 4.07, 'transportation_modes': 'Road', 'routes': 'Route_B', 'costs': 563.07, 'demurrage_cost_prediction': 54.42549999999999, 'demurrage_bin': 1}, {'sku': 2409620, 'estimated_price': 8251.96252, 'number_of_products_sold': 696.1544255, 'stock_levels': 44.24509383, 'lead_times': 7.764919693, 'order_quantities': 69.66251389, 'shipping_times': 5.0, 'shipping_carriers': 'Carrier B', 'shipping_costs': 533.0, 'location': 'Mumbai', 'production_volumes': 554.9156217, 'manufacturing_lead_time': 6.573059301, 'manufacturing_costs': 69.45, 'inspection_results': 'Fail', 'defect_rates': 1.56, 'transportation_modes': 'Air', 'routes': 'D route', 'costs': 506.19, 'demurrage_cost_prediction': 59.601800000000004, 'demurrage_bin': 1}, {'sku': 3210626, 'estimated_price': 56945.72832, 'number_of_products_sold': 161.4287572, 'stock_levels': 48.13790727, 'lead_times': 17.33553905, 'order_quantities': 60.25554524, 'shipping_times': 1.0, 'shipping_carriers': 'Carrier A', 'shipping_costs': 220.0, 'location': 'Bangalore', 'production_volumes': 128.6387942, 'manufacturing_lead_time': 8.124497762, 'manufacturing_costs': 92.2, 'inspection_results': 'Fail', 'defect_rates': 1.89, 'transportation_modes': 'Rail', 'routes': 'D route', 'costs': 786.93, 'demurrage_cost_prediction': 51.75320000000002, 'demurrage_bin': 1})]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2375)
[2024-06-22T12:08:03.149+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-22T12:08:03.163+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
